spring:
  application:
    name: api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/REALWORLD
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    user:
      name: admin
      password: admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html

jwt:
  secret: your-secret-key
  expiration: 86400000 # 1 day in milliseconds
